spring:
  datasource:
    username: duchong
    password: Prepay@2019
    url: jdbc:mysql://127.0.0.1:13306/prepay?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      web-stat-filter:
        enabled: true
        url-pattern: '/*'
        exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*'
        session-stat-enable: true
      stat-view-servlet:
        url-pattern: '/druid/*'
        reset-enable: false
        login-username: zanclick
        login-password: ZanClick666
        enabled: true
      filter:
        stat:
          slow-sql-millis: 5000
  redis:
    host: 127.0.0.1
    port: 26378
    password: 
    timeout: 3000ms
    database: 6
    lettuce:
      pool:
        max-wait: 2000ms
        min-idle: 50
        max-idle: 100
        max-active: 200

#预授权通知接口
authorize:
  notify: http://116.62.11.124/api/open/authorize/notify

# H5接口访问密钥
h5:
  key: 12345678qwertyui
  server: http://116.62.11.124/h5

 #支付超时时间
timeout:
  authorize:
    prepay: 10

#广州移动配置信息
guangzhou:
  request:
    appId: 101102
    routeType: 1
    signMethod: RSA
    notify: https://221.179.11.204/eaop/rest/BSS/commodity/freezenotify/v1.1.1
    key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCeIJM4VsDUclGFWIBa0Hzq+6/GDxMMU1T+ceWdDZm7LkFYBo1hIUD7S1VT2Qz8OjnsA2R+tsjvzZ7MRFQt4K0+1++dqvtxJsrgkhDKuyzs0nGHZs63wI2m19JI1QFncfABQ5n61C2zAvDEnKLIgQEInwE9upDwTWks7lThzzQXCLuyzCHdcLEar2nyaIXkzOV0E0S/r/1OJsSSOkHUkaCVbx55u+ShlRgU4V/HSZ/JKD4bIUJbUzBCxpHKJp7Yr2qa0YN3ob2F5Ple4NV07Y/FvbcTnt0rP58ApJs8/a3Pfq6kD5u7YT85bVhtkcrkx0p1gpioQ+w97C9pmaimP0KxAgMBAAECggEARYtAFDwbTJQGhGXa9ZXSCqqssKe6keYocEt5V6w+m1MJjAQ9s6UjZiHIojrIejnFdaY8UXpkPwsott+qQg8ZQpVHngkv0qDkAwZaej790B3xrkIp0ijOY71xj3SWzH8Qtg2cL/OXMa6uY1ocQaBy6u67ZgGicv0or4kWLcWqPCJ7FwLrPeld9D1Acjpbcmh+cl4hMz9BeN02k4ZuMF4cpir4bTqt1uAphqYFXUKahNJXsTDfM+qelr9oeg5xBlV6hCbGpiCapWBOV2lLzJG+70xEo1EtosoTRQKeDSvd/hFOBD4tT4X+eIZMq/mIqZOjyWPCq3hij5sXmmZRKfbYAQKBgQDO6c/2lxEzTh527w+LZzWR48DKcc89cCId6fmDy4fd1kojos1IhibJl3qw8hNJJEWDRnEu4ryyauDY8548Y0egCindpMPDoYqW2+nxDgvWxsmELubaNJszg2/nHTf+Hv8MAifVj674K7gX71/vkNkl/J2Rz3gA+rEQzpsTRIzngQKBgQDDo+dJIxJD8AwSTupnK5qRzwE414852Ul2l15ZD1m0o89GLFamidBXHaH6SkQG+r9JcOngEu/xzQIfv0x3oDzkvjT+kktQJK8w0giMHjcE2Jd0pig081KyrQkMjZrvzsYjYxCgHWcjOolWrV9+oKhK9PEa/2Mxhs6FHWFDn0hzMQKBgQDKRoDrjBtgkInvsxz7JtaT3JboUgJLCYgQvl8SnLIiCA9KbylIMP1SLiffO4fnBPJ/tymGsFnQAfP1o5OZbWTj64uqBhzq7s1RVYOKCDVCrerqsf80aiEfZurKgSHv59Vlo+XVPTXLntHFdFnRFUVzgVV46d1i97CJwbCQUX9+AQKBgFWxW0Nby0pawM7cJiwem0u2olBliuTJ2jXJw5e6843+GnIgRawYvVsLLcHV+coc1uCyRp7RbKw7Ie0J+9KCK2n+LnQ7XCW0i9AUj43gRjUnMd/0T7QxyE1fIZGQDQdxSLSDVersNhrmLvX6ZtOuR0jd1SYAK1CsPZVs8weNo0xhAoGBAJOTOxZgHS+SrXv34v5sCNqya/yEiGQBmdYUnZ7Fnxkv23MemP8lVNGutzmW4J7/MfXW8nIKm6XUtr5oqup19cmaTt4Cggz2f7T6M+2fn4KtXoN7wXwDTGUyfOPNVc3YMXVfEQjxAbXVMNw2X9a7T5+ijYnQdl3JzDPU9p13468v