spring:
  datasource:
    username: lvlu
    password: Lvlu2018.
    url: jdbc:mysql://172.16.4.201/zanclick_prepay?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      web-stat-filter:
        enabled: true
        url-pattern: '/*'
        exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*'
        session-stat-enable: true
      stat-view-servlet:
        url-pattern: '/druid/*'
        reset-enable: false
        login-username: zanclick
        login-password: ZanClick666
        enabled: true
      filter:
        stat:
          slow-sql-millis: 5000
  redis:
    host: 172.16.4.201
    port: 6379
    password: tuchuan2017
    timeout: 3000ms
    database: 6
    lettuce:
      pool:
        max-wait: 2000ms
        min-idle: 50
        max-idle: 100
        max-active: 200

activemq: #MQ消息中间件
  broker-url: failover:(tcp://172.16.4.201:61616)
  user: system
  password: ba4643ac16d4d15f131e61e6b7936850
  enabled: true
  max-connections: 50
  expiry-timeout: 10000
  idle-timeout: 30000

#预授权通知接口
authorize:
  #notify: http://api.ngrok.zanclick.cn/api/open/authorize/notify
  notify: http://prepay.utools.club/api/open/authorize/notify

excelDownloadUrl: http://172.16.4.9:8888/api/open/downloadExcel/

# H5接口访问密钥
h5:
  key: 12345678qwertyui
  server: http://172.16.4.9:8082
 #支付超时时间
timeout:
  authorize:
    prepay: 10

#广州移动配置信息
guangzhou:
  request:
    appId: 502004
    routeType: 1
    signMethod: RSA
    notify: https://221.179.35.152:22418/eaop/rest/BSS/commodity/freezenotify/v1.1.1
    key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQChNEXuDo+u42Q36QHXt1Y7WLXKWe1VVTuBdznSiz6wgFIo1oSTCqjSXquPd9mIFRAj6tTLobCgKkI9pDY0KWBIgaN5Px5u7uD02Umrx2Wf08QuPRSKySg4QopvBl1m8R3I4fn/37njrjO4DbhLfwusl1yug5NScu2oxTm+UR/HpkTq5eWaYC4hG+Ny6waG13/iX8XiHRoTVDImSbG874WK8RKJWD3/+qAX2UNOQ9ycuYG7PrW+byJ/ukHtn3DLRkiZGz8uM+CliAJHkVYXjTivIdMerdVFbfAVypRehQMLvLV9/bwS8LT4WXgEov4vTASuqlgws4JmZu/kJxm91fkdAgMBAAECggEABnd3Wq5g2y4qBggl18Z2Ahlz6XMkDylFItNqkWSeliv/n73DQbbKwO2lSjMPmeLma9puwOBymmo3kAt3VS5Xu3Df4uxCR0bz5T6WMvrju76d/xDaMxsQrvkUXpHNy2RewoE2KyqJZXXGg1qhiv3EtR65TBLhJQyRNhT7VQQiFzsm8kwhK56FxKAXrylSs9e3eCL7DbvQRBi9oBT57EJcCuuK3yyJ2rfWsAm1c2wEVTlrTaevwGTk7IEDMnLRtmYRUKxtmf/BSQubbU2snefChKaZ+0OvReC3YUtFJz8mohjFHhQNs9zzNQPpHl6Lak6YMO8r3cOdznfZKiXJJO7DIQKBgQDYBBNubuLNPSV19ZpmKyTngX67bztY7S2dvkHJa9XZgkTi36RNZriIAHs3fyqJ7fCurpjw/3jvAT1JLPuBNNtwbyr08RZ4xUa6/XzgaemYkYc8SADCOqJHzUP+EyxLOQt6bpo8Gl5BV8f4NKBVe9ihzaiIFatDK6nOT/uSjt3ItQKBgQC/CvDmAfC7C7SSXr0EvHKvw0gkkryOnrNpYjonGdxkulNmal5xAwmsmc/UlZoTwTZq8qY3QGh9KyQY12y1VfnqsLsxj6eNxkQnW+PHnKi+v7jopaGhDuLnrHeMNt47QXdebBLMB4EcrKGmimt0t4ofo242EF8M4MwpqU4qUJK3yQKBgFDkhdpPEAPHqCWaSa2E7pb7OVg7eT/94Z02yDADf9uqGt3S3hZWJzhW5c2Mg4OPZRglLgThxonKLwceHzjtcFeUacO8HKwxRCF2F7N6Ng36QWhjllUl2+uDhLi6uVWaESBSFtP3E+DoXGwoWPpqHF/LQhdj9fR7f2VRMmZZtdgZAoGBALefvIxXsRsX1SgbB3NV7qYh/WWp5LLwt2HDmEGdCcmHjkISW1Qkp1fPP4QFh2MVg0iokjrpHYWxwbBe344sZVq/JC4u9c2/lCKAoB9s5ITzord6/C/iLxafHwkWc+RguGt5VVfmnqMBCx8YTNCS2aAvZe9xLOsj5xjkMs1ZRKyBAoGAJ2jzyjXfLW6NSw4Hf5V8Ur6wio0XFkibkvDx3meMyY8OWSfC1x6+fnSxvxVVi/SgrkEuUCz1zkfuj3faVf+b43pyrgIEqaBXta+Nt5iIV85sOsaroKCcsN7f5MPP2J8uGszzBDlBYohnpB/BthCnWcmtrLjcZ8LTrkknLXCbmXM=

#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl